src/bean/AddRestaurantBean.java
package bean;

public class AddRestaurantBean {

	 private String userName;
	 private String password;
	 private String nameRestaurant;
	 private String location;
	 private String nameDispatcher;
	 private int phone;
	 private String description;
	 
	 
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getNameRestaurant() {
		return nameRestaurant;
	}
	public void setNameRestaurant(String nameRestaurant) {
		this.nameRestaurant = nameRestaurant;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getNameDispatcher() {
		return nameDispatcher;
	}
	public void setNameDispatcher(String nameDispatcher) {
		this.nameDispatcher = nameDispatcher;
	}
	public String getLocation() {
		return location;
	}
	public void setLocation(String location) {
		this.location = location;
	}
	public int getPhone() {
		return phone;
	}
	public void setPhone(int phone) {
		this.phone = phone;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	
}

src/bean/CartBean.java
package bean;

import java.util.ArrayList;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.util.ArrayList;

public class CartBean {
 private ArrayList alCartItems = new ArrayList();
 private double dblOrderTotal ;
  
 public int getLineItemCount() {
  return alCartItems.size();
 }
  
 public void deleteCartItem(String strItemIndex) {
  int iItemIndex = 0;
  try {
   iItemIndex = Integer.parseInt(strItemIndex);
   alCartItems.remove(iItemIndex - 1);
   calculateOrderTotal();
  } catch(NumberFormatException nfe) {
   System.out.println("Error while deleting cart item: "+nfe.getMessage());
   nfe.printStackTrace();
  }
 }
  
 public void updateCartItem(String strItemIndex, String strQuantity) {
  float dblTotalCost = 0;
  float dblUnitCost = 0;
  int iQuantity = 0;
  int iItemIndex = 0;
  CartItem cartItem = null;
  try {
   iItemIndex = Integer.parseInt(strItemIndex);
   iQuantity = Integer.parseInt(strQuantity);
   if(iQuantity>0) {
    cartItem = (CartItem)alCartItems.get(iItemIndex-1);
    dblUnitCost = (float) cartItem.getUnitCost();
    dblTotalCost = dblUnitCost*iQuantity;
    cartItem.setQuantity(iQuantity);
    cartItem.setTotalCost(dblTotalCost);
    calculateOrderTotal();
   }
  } catch (NumberFormatException nfe) {
   System.out.println("Error while updating cart: "+nfe.getMessage());
   nfe.printStackTrace();
  }
   
 }
  
 public void addCartItem(String strModelNo, String strDescription,
String strUnitCost, String strQuantity) {
  float dblTotalCost = 0;
  float dblUnitCost = 0;
  int iQuantity = 0;
  double ttl=0;
  CartItem cartItem = new CartItem();
  try {
   dblUnitCost = Float.parseFloat(strUnitCost);
   iQuantity = Integer.parseInt(strQuantity);
   if(iQuantity>0) {
    dblTotalCost = dblUnitCost*iQuantity;
    cartItem.setPartNumber(strModelNo);
    cartItem.setModelDescription(strDescription);
    cartItem.setUnitCost(dblUnitCost);
    cartItem.setQuantity(iQuantity);
    cartItem.setTotalCost(dblTotalCost);
    alCartItems.add(cartItem);
     ttl = calculateOrderTotal();
  
   }
   
  } catch (NumberFormatException nfe) {
   System.out.println("Error while parsing from String to primitive types: "+nfe.getMessage());
   nfe.printStackTrace();
  }
 }
  
 public void addCartItem(CartItem cartItem) {
  alCartItems.add(cartItem);
 }
  
 public CartItem getCartItem(int iItemIndex) {
  CartItem cartItem = null;
  if(alCartItems.size()>iItemIndex) {
   cartItem = (CartItem) alCartItems.get(iItemIndex);
  }
  return cartItem;
 }
  
 public ArrayList getCartItems() {
  return alCartItems;
 }
 public void setCartItems(ArrayList alCartItems) {
  this.alCartItems = alCartItems;
 }
 public double getOrderTotal() {
  return dblOrderTotal;
 }
 public void setOrderTotal(double dblOrderTotal) {
  this.dblOrderTotal = dblOrderTotal;
 }
  
 protected double calculateOrderTotal() {
  double dblTotal = 0;
  for(int counter=0;counter<alCartItems.size();counter++) {
   CartItem cartItem = (CartItem) alCartItems.get(counter);
   dblTotal+=cartItem.getTotalCost();
   
    
  }
  setOrderTotal(dblTotal);
  return dblTotal;
 }
 
}

src/bean/CartItem.java
package bean;

public class CartItem {
    private String strPartNumber;
    private String strModelDescription;
    private float dblUnitCost;
    private int iQuantity;
    private float dblTotalCost;
     
    public String getPartNumber() {
        return strPartNumber;
    }
    public void setPartNumber(String strPartNumber) {
        this.strPartNumber = strPartNumber;
    }
    public String getModelDescription() {
        return strModelDescription;
    }
    public void setModelDescription(String strModelDescription) {
        this.strModelDescription = strModelDescription;
    }
    public double getUnitCost() {
        return dblUnitCost;
    }
    public void setUnitCost(float dblUnitCost) {
        this.dblUnitCost = dblUnitCost;
    }
    public int getQuantity() {
        return iQuantity;
    }
    public void setQuantity(int quantity) {
        iQuantity = quantity;
    }
    public double getTotalCost() {
        return dblTotalCost;
    }
    public void setTotalCost(float dblTotalCost) {
        this.dblTotalCost = dblTotalCost;
    }
}

src/bean/LogInBean.java
package bean;

public class LogInBean {


	 private String userName;
	 private String password;

	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
}

src/bean/SignUpBean.java
package bean;

public class SignUpBean {

	 private String userName;
	 private String password;
	 private String name;
	 private String address;
	 
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
}

src/modal/AddRestaurantServlet.java
package modal;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class AddRestaurant
 */
@WebServlet("/AddRestaurant")
public class AddRestaurantServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public AddRestaurantServlet() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		response.getWriter().append("Served at: ").append(request.getContextPath());
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}

src/modal/LoginServlet.java
package modal;

import java.io.IOException;
 
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
 
import bean.LogInBean;
import dao.LoginDao;
 
public class LoginServlet extends HttpServlet {
private static final long serialVersionUID = 1L;
 
public LoginServlet() {
}
 
protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException 
{
	
 String userName = request.getParameter("userName");
 String password = request.getParameter("password");
 
 LogInBean loginBean = new LogInBean();
 
 loginBean.setUserName(userName);
 loginBean.setPassword(password);
 
 LoginDao loginDao = new LoginDao();

 try
 {
 String userValidate = loginDao.authenticateUser(loginBean);
 
 if(userValidate.equals("Admin_Role"))
 {
 System.out.println("Admin's Home");
 
 HttpSession session = request.getSession(); //Creating a session
 session.setAttribute("adminsession", loginBean); //setting session attribute
 request.setAttribute("userName", userName);
 
 request.getRequestDispatcher("/indexAdmin.jsp").forward(request, response);
 }
 
 else if(userValidate.equals("User_Role"))
 {
 System.out.println("User's Home");
 
 HttpSession session = request.getSession();
 session.setMaxInactiveInterval(10*60);
 session.setAttribute("usersession", loginBean);
 request.setAttribute("userName", userName);
 
 request.getServletContext().getRequestDispatcher("/indexClient.jsp").forward(request, response);
 }
 
 else if(userValidate.equals("Dispatcher_Role"))
 {
 System.out.println("Dispatcher's Home");
 
 HttpSession session = request.getSession();
 session.setMaxInactiveInterval(10*60);
 session.setAttribute("dispatchersession", loginBean);
 request.setAttribute("userName", userName);
 
 request.getServletContext().getRequestDispatcher("/indexDispatcher.jsp").forward(request, response);
 }
 
 else
 {
 System.out.println("Error message = "+userValidate);
 request.setAttribute("errMessage", userValidate);
 
 request.getRequestDispatcher("/LogIn.jsp").forward(request, response);
 }
 }
 catch (IOException e1)
 {
 e1.printStackTrace();
 }
 catch (Exception e2)
 {
 e2.printStackTrace();
 }
} //End of doPost()
}

src/modal/LogoutServlet.java
package modal;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.RequestDispatcher;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 * Servlet implementation class LogoutServlet
 */
@WebServlet(name = "Logout", urlPatterns = { "/Logout" })
public class LogoutServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public LogoutServlet() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		 HttpSession session = request.getSession(false); //Fetch session object
		 
		 if(session!=null) //If session is not null
		 {
		 session.invalidate(); //removes all session attributes bound to the session
		 request.setAttribute("errMessage", "You have logged out successfully");
		 RequestDispatcher requestDispatcher = request.getRequestDispatcher("/firstPage.jsp");
		 requestDispatcher.forward(request, response);
		 System.out.println("Logged out");
		 }
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}

src/servlets/PlaceOrderController.java
package servlets;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class PlaceOrderController
 */
@WebServlet("/PlaceOrderController")
public class PlaceOrderController extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public PlaceOrderController() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		response.getWriter().append("Served at: ").append(request.getContextPath());
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}

WebContent/Logout.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>

 <form name="form" action="<%=request.getContextPath()%>
/LoginServlet" method="get">

</form>

</body>
</html>

WebContent/ModelList.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>

</body>
</html>

WebContent/PlaceOrder.jsp
<%@page import="java.util.ArrayList" %>
<%@page import="entities.Order" %>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<link rel="stylesheet" type="text/css"  href="css2/style.css">
<title>Confirmation</title>
<style>
table {
  border-collapse: collapse;
  width: 92%;
}

.div2{
 text-align: center;
}
th, td {
  text-align: left;
  padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
  background-color: #4CAF50;
  color: white;
}
</style>
</head>
<body>

<%
  
  

%>


    
    <%
    Order order = (Order)session.getAttribute("orderdet");
    ArrayList<String> products = new ArrayList<>();
  	 ArrayList<Integer> quantities = new ArrayList<>();
  	 ArrayList<Float> unitPrices = new ArrayList<>();
  
  	 products = order.getProducts();
  	 quantities= order.getQuantities();
  	 unitPrices = order.getUnitPrices();
  	// totalPrices = order.getTotalprices();
  	float finalPrice =0 ;
  	for(int counter=0;counter<products.size();counter++) {
  	   finalPrice += quantities.get(counter)*unitPrices.get(counter);
  			   }
  	
    order.setFinalPrice(finalPrice);
  	// float finalPrice = order.getFinalPrice();
  	session.setAttribute("finalorder", order);
  	
  	
  	request.setAttribute("finalPrice", finalPrice);
  	
  	
  	session.setAttribute("finalPrice", finalPrice);
  	 int maxx = products.size();
  	 %>
  	
  	<table>
  <tr>
    <th>Product</th>
    <th>Quantity</th>
    <th>Price</th>
  </tr>
<% 
  	for(int i=0; i< products.size();i++)
  	 {
  		 %> 
  	 
    
    <tr>
    <td><%= products.get(i)%></td>
    <td><%=quantities.get(i)%></td>
    <td><%=unitPrices.get(i)%></td>
  </tr>

   <%
  	 }
  	 %>
</table>
 <div class="gap-20"></div>
           
            
            
           <div class="div2">
            <h2><%=finalPrice %>$</h2>
            <div class="gap-20"></div>
            <h3>Forgot something?</h3>
            <input type="button" class="butonulMeu2" value="Back to cart" onclick="history.back()">
              <div class="gap-20"></div>
               <div class="gap-20"></div>

             <h3>Confirm order</h3>
            <form action="<%=request.getContextPath()%>/sendNotification?finalPrice=<%=session.getAttribute("finalPrice")%>" method="post">
            <input type="submit" class="butonulMeu2" name="place_order" value="  Payment  " />
           </form>
           </div>

</body>
</html>

WebContent/ShoppingCart.jsp
<%@page import="java.util.ArrayList" %>
<%@page import="entities.Order" %>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>Shopping Cart</title>
<style>
body{}
table{
width:800 px;
margin: auto;
text-align : center;
table-layout:fixed;
}

table, tr,td ,th{
color:black;
border-collapse: collapse;
border:1px solid #4CAF50 ;
font-size: 18px;
font-family:Arial;
background:  linear-gradient(top,#3c3c3c 0%, #4CAF50 100%);
background: -webkit-linear-gradient(top,#3c3c3c 0% , #4CAF50 100%);
}

</style>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link rel ="stylesheet" type="text/css" href="css/styleRestView.css"> 
<link rel="stylesheet" type="text/css"  href="css2/style.css">
<link rel="stylesheet" type="text/css" href="css2/nivo-lightbox/nivo-lightbox.css">
<link rel="stylesheet" type="text/css" href="css2/nivo-lightbox/default.css">
</head>
 
<body>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<div id="main">
    <nav>
    <ul>
         <li>Shopping Cart</li>
      </ul>
    
    </nav>
 </div>
            <div class="gap-20"></div>
            <div class="gap-20"></div>
            <div class="gap-20"></div>
        <%
        String cartEmpty = (String)session.getAttribute("cartempty");
      //  if(cartEmpty.equals("yes")){
        //	"${cart.lineItemCount}" = 0 ;
      //  }
     ArrayList<String> products = new ArrayList<>();
   	 ArrayList<Integer> quantities = new ArrayList<>();
   	 ArrayList<Float> unitPrices = new ArrayList<>();
   	 ArrayList<Float> totalPrices = new ArrayList<>();
         %>

<table width="75%" border="1">
  <tr bgcolor="#4CAF50">
    <td>Product</td>
    <td>Quantity</td>
    <td><strong>Unit
      Price</font></strong></td>
    <td>Total</td>
  </tr>
  <jsp:useBean id="cart" scope="session" class="bean.CartBean" />
  <c:if test="${cart.lineItemCount==0}">
  <tr>
  <td colspan="4"><font size="3.5" face="Verdana, Arial, Helvetica, sans-serif">- Cart is currently empty -<br/>
  </tr>
  </c:if>
  <c:forEach var="cartItem" items="${cart.cartItems}" varStatus="counter">
    <%//products.add("${cart.cartItems}"); %>
  <form name="item" method="POST" action="servlets/CartController">
  <tr>
    <td><c:out value="${cartItem.partNumber}"/><br/>
      <c:out value="${cartItem.modelDescription}"/></td>
    <td><input type='hidden' name='itemIndex' value='<c:out value="${counter.count}"/>'><input type='text' name="quantity" value='<c:out value="${cartItem.quantity}"/>' size='2'><%// quantities.add(Integer.parseInt("${cartItem.quantity}")); %> <input type="submit" name="action" value="Update">
         <input type="submit" name="action" value="Delete"></td>
    <td>$<c:out value="${cartItem.unitCost}"/></td>
    <%
   // System.out.println(${cartItem.unitCost});
   // unitPrices.add(Float.parseFloat(${cartItem.unitCost})); %>
    <td>$<c:out value="${cartItem.totalCost}"/></td>
        <%//totalPrices.add(Float.parseFloat("${cartItem.totalCost}")); %>
  </tr>
  </form>
  </c:forEach>
  <tr>
    <td colspan="2"> </td>
    <td> </td>
    <td><font size="3" face="Verdana, Arial, Helvetica, sans-serif">Subtotal: $<c:out value="${cart.orderTotal}"/></font></td>
  </tr>
</table>


            <div class="gap-20"></div>
            <div class="gap-20"></div>
            
<input type="button" class="butonulMeu3" value="Menu" onclick="history.back()">


  <form name="item" method="POST" action="servlets/CartController">
      <input type="button" class= "butonulMeu4" name="action" value="Delete All">
      </form>
 
 <input type="button" class="butonulMeu5" onclick="window.location.href='http://localhost:8010/FoodDelivery/PlaceOrder.jsp'" name="place_order" value="Place order" />
 

<script type="text/javascript" src="js/jquery.1.11.1.js"></script> 
<script type="text/javascript" src="js/bootstrap.js"></script> 
<script type="text/javascript" src="js/SmoothScroll.js"></script> 
<script type="text/javascript" src="js/nivo-lightbox.js"></script> 
<script type="text/javascript" src="js/jquery.isotope.js"></script> 
<script type="text/javascript" src="js/jqBootstrapValidation.js"></script> 
<script type="text/javascript" src="js/contact_me.js"></script> 
<script type="text/javascript" src="js/main.js"></script>
</body>
</html>

WebContent/addDish.jsp
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="css/addrestaurantstyle.css">
  </head>
  <body>
  
  
  <div id="main">
    <nav>
       <ul>
         <li><a href="indexAdmin.jsp">Home</a></li>
         <li><a href="pageRestaurantAView.jsp">Restaurants</a></li>
         <li><a href="addRestaurant.jsp">AddRestaurant</a></li>
          <li><a href="<%=request.getContextPath()%>/LogoutServlet">Logout</a></li>
        
      </ul>
    
    </nav>
 </div>
       
      
       <form action="addDish_controller.jsp">
       
     <div class="login-box">
        <h1>New Dish</h1>  
         <div class="textbox">
    <i class="fas fa-user"></i>
    <input type="text" placeholder="Dish Name" name= "dishName" value="" >
  </div>
        
         <div class="textbox">
    <i class="fas fa-lock"></i>
    <input type="text" placeholder="price" name= "dishPrice" value="" >
  </div>
          
        
        <div class="textbox">
    <i class="fas fa-lock"></i>
    <input type="text" placeholder="Photo link" name= "dishPhoto" value="" >
  </div>
        
  
         <input class ="btn" type="submit" value="Add">
       
       </div>
       
       </form>
 

</body>
</html>

WebContent/addRestaurant.jsp
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="css/addrestaurantstyle.css">
  </head>
  <body>
  
  
  <div id="main">
    <nav>
       <ul>
         <li><a href="indexAdmin.jsp">Home</a></li>
         <li><a href="pageRestaurantAView.jsp">Restaurants</a></li>
         <li><a href="addRestaurant.jsp">AddRestaurant</a></li>
         
         <li><a href="<%=request.getContextPath()%>/LogoutServlet">Logout</a></li>
      </ul>
    
    </nav>
 </div>
       
      
       <form action="addRestaurant_controller.jsp">
       
     <div class="login-box">
        <h1>New Restaurant</h1>  
         <div class="textbox">
    <i class="fas fa-user"></i>
    <input type="text" placeholder="Restaurant Name" name= "restaurantName" value="" >
  </div>
        
         <div class="textbox">
    <i class="fas fa-lock"></i>
    <input type="text" placeholder="Location" name= "restaurantLocation" value="" >
  </div>
         
         
         <div class="textbox">
    <i class="fas fa-user"></i>
    <input type="text" placeholder="Description" name= "restaurantDescription" value="" >
  </div>
  
   
       <div class="textbox">
    <i class="fas fa-lock"></i>
    <input type="text" placeholder="Dispatcher username" name= "userName" value="" >
  </div>
  
       <div class="textbox">
    <i class="fas fa-lock"></i>
    <input type="text" placeholder="Dispatcher password" name= "password" value="" >
  </div>
  
      <div class="textbox">
    <i class="fas fa-lock"></i>
    <input type="text" placeholder="Dispatcher name" name= "dispatcherName" value="" >
  </div>
  
  
      
        <div class="textbox">
    <i class="fas fa-lock"></i>
    <input type="text" placeholder="Dispatcher phone" name= "dispatcherPhone" value="" >
  </div>     
  
        
        <div class="textbox">
    <i class="fas fa-lock"></i>
    <input type="text" placeholder="Photo link" name= "photo" value="" >
  </div>
        
  
         <input class ="btn" type="submit" value="Add">
       
       </div>
       
       </form>
 

</body>
</html>

WebContent/cardPayment.jsp
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]> <html class="lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]> <html class="lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Checkout Form</title>
  <link rel="stylesheet" href="css2/cardStyle.css">
  <!--[if lt IE 9]><script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>
 <form action="card_controller.jsp">
  <div class="checkout">
    <div class="checkout-header">
      <h1 class="checkout-title">
  
      
    
      </h1>
    </div>
    
       
    <p>
      <input type="text" class="checkout-input checkout-name" placeholder="Your name" autofocus name="Name_Client">
      <input type="text" class="checkout-input checkout-exp" placeholder="MM">
      <input type="text" class="checkout-input checkout-exp" placeholder="YY">
    </p>
    <p>
      <input type="text" class="checkout-input checkout-card" placeholder="4111 1111 1111 1111" name="Card_Number">
      <input type="text" class="checkout-input checkout-cvc" placeholder="CVC">
    </p>
    <p>
      <input type="submit" value="Purchase" class="checkout-btn">
    </p>
 
  </div>

    </form>

</body>
</html>